# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: 빌드 & 테스트

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: gradlew 권한 변경
      run: chmod +x gradlew
      
    - name: 빌드
      run: ./gradlew build
      
    - name: 테스트
      run: ./gradlew test
      
    - name: jar 파일 upload
      uses: actions/upload-artifact@v2.2.4
      with:
        name: jar-file
        path: ./build/libs/*release.jar
        
  delivery:
    needs: [ build-test ]
    runs-on: ubuntu-latest
    
#     if: github.event_name == 'push'
    steps:
    - name: jar 파일 download
      uses: actions/download-artifact@v2.0.10
      with:
        name: jar-file
        
    - name: jar 파일 push to Release branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: release
        FOLDER: ./
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
        
